### PR TITLE
WIP: Massive rewrite, dropping diesel for sqlx

### PR DESCRIPTION
**Pull request by phated**
This is a massive rewrite that drops `diesel` in favor of `sqlx`.

It also upgrades `async-graphql` to get the new DataSource work that really cleans things up a lot.

I'm using my fork of `sqlx` because I rely heavily on custom types and they don't support it yet.

This won't build successfully after a fresh migrate because the OIDs of my Postgres types won't be the same. However, it will build using the offline support of my fork, which is pretty cool.

### CODE REVIEW

**Comment by sunli829** [comment]
I've always wanted to ask, how does this program work? Because I don't have the initial data for the database. 😁

**Comment by sunli829** [comment]
I deleted the `ctx` parameter of `DataSource::query`, I didn't think it was necessary. If the `DataSource` object was created temporarily, it would be more convenient to use the `connection::query` function now.

**Comment by phated** [comment]
> I've always wanted to ask, how does this program work? Because I don't have the initial data for the database

My next task is to create mutations and load in some data.

> I deleted the ctx parameter of DataSource::query, I didn't think it was necessary. If the DataSource object was created temporarily, it would be more convenient to use the connection::query function now.

I believe I need Context because I will be using Dataloader for all my data access in the future.

**Comment by sunli829** [comment]
I see, so you can use connection::query, DataLoader to pass in a closure.

**Comment by phated** [comment]
@sunli829 you inspired me to have proper seed data so I added mutations and a graphql file that seeds the database using the mutations using `npm run seed`

However, there will still be issues starting this branch because sqlx doesn't support custom postgres types yet. I have to update my fork each time I seed the database 😦

**Comment by phated** [comment]
This is actually ready to be merged. With the new sqlx 0.4.0 stuff, I can reliably provide my fork that has custom types for this application that aren't tied to an OID.

I'll get this merged and work on some documentation for getting it running locally.

**Comment by phated** [comment]
@sunli829 this has finally been merged and I added setup instructions to the README. If you ever want to try this project, I'm happy to receive your feedback!

**Comment by sunli829** [comment]
I don't understand the Transformers card game, but it looks pretty good. 😁

**Pull request merged**
